#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Assumes you are using Amazon Linux 2 or Ubuntu

command -v docker-compose >/dev/null 2>&1 || {
        echo >&2 "I require Docker Compose but it's not installed.";

        # https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9
        sudo yum install python3 -y;
        sudo amazon-linux-extras install docker -y;
        sudo service docker start;
        sudo usermod -a -G docker ec2-user;
        sudo chkconfig docker on;
        sudo yum install -y git;

        # https://docs.docker.com/compose/install/
        sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose;
        sudo chmod +x /usr/local/bin/docker-compose;
}
